# This file is processed when the IAR compiler is used for an assembler file

INCLUDE(Compiler/IAR)

SET(CMAKE_ASM_COMPILE_OBJECT  "<CMAKE_ASM_COMPILER> <SOURCE> <DEFINES> <FLAGS> -o <OBJECT>")

IF ("${IAR_TARGET_ARCHITECTURE}" STREQUAL "ARM")
  SET(CMAKE_ASM_SOURCE_FILE_EXTENSIONS s;asm;msa)

ENDIF ("${IAR_TARGET_ARCHITECTURE}" STREQUAL "ARM")


IF ("${IAR_TARGET_ARCHITECTURE}" STREQUAL "AVR")
  SET(CMAKE_ASM_SOURCE_FILE_EXTENSIONS s90;asm;msa)

ENDIF ("${IAR_TARGET_ARCHITECTURE}" STREQUAL "AVR")
