# This file is processed when the IAR compiler is used for a C++ file

INCLUDE(Compiler/IAR)

SET(CMAKE_CXX_COMPILE_OBJECT  "<CMAKE_CXX_COMPILER> <SOURCE> <DEFINES> <FLAGS> -o <OBJECT>")

SET(CMAKE_CXX_CREATE_PREPROCESSED_SOURCE "<CMAKE_CXX_COMPILER> <SOURCE> <DEFINES> <FLAGS> --preprocess=cnl <PREPROCESSED_SOURCE>")
SET(CMAKE_CXX_CREATE_ASSEMBLY_SOURCE     "<CMAKE_CXX_COMPILER> <SOURCE> <DEFINES> <FLAGS> -lAH <ASSEMBLY_SOURCE> -o <OBJECT>.dummy")



IF ("${IAR_TARGET_ARCHITECTURE}" STREQUAL "ARM")

  SET(CMAKE_CXX_LINK_EXECUTABLE "<CMAKE_LINKER> <OBJECTS> <CMAKE_CXX_LINK_FLAGS> <LINK_FLAGS> <LINK_LIBRARIES> -o <TARGET>")
  SET(CMAKE_CXX_CREATE_STATIC_LIBRARY "<CMAKE_AR> <TARGET> --create <LINK_FLAGS> <OBJECTS> ")

ENDIF ("${IAR_TARGET_ARCHITECTURE}" STREQUAL "ARM")


IF ("${IAR_TARGET_ARCHITECTURE}" STREQUAL "AVR")
  SET(CMAKE_CXX_OUTPUT_EXTENSION ".r90")
  IF(NOT CMAKE_CXX_LINK_FLAGS)
    SET(CMAKE_CXX_LINK_FLAGS "-Fmotorola")
  ENDIF(NOT CMAKE_CXX_LINK_FLAGS)

  SET(CMAKE_CXX_LINK_EXECUTABLE "<CMAKE_LINKER> <OBJECTS> <CMAKE_CXX_LINK_FLAGS> <LINK_FLAGS> <LINK_LIBRARIES> -o <TARGET>")
  SET(CMAKE_CXX_CREATE_STATIC_LIBRARY "<CMAKE_AR> -o <TARGET> <OBJECTS> ")

ENDIF ("${IAR_TARGET_ARCHITECTURE}" STREQUAL "AVR")

# add the target specific include directory:
GET_FILENAME_COMPONENT(_compilerDir "${CMAKE_C_COMPILER}" PATH)
GET_FILENAME_COMPONENT(_compilerDir "${_compilerDir}" PATH)
INCLUDE_DIRECTORIES("${_compilerDir}/inc")
